package com.mygdx.demonestate.weapon;

/**
 * Created by David on 3/17/2017.
 */
public enum WeaponType {
   DAGGER, SWORD, SPEAR, BAT,
   KATANA, HALBERD, LIGHTSABER,
   GRAVHAMMER, KUSANAGI, THORS_HAMMER,
   PISTOL, SHURIKEN, STUN_GUN, DEAGLE,
   UZI, LASER_PISTOL, HOMING_SHURIKEN,
   STICKY_BOMB, DEATHERANG, QUICKSHOT
}
